site_name: DOES VTT
site_url: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
logo: docs/DOES_Logo.png
nav:
  - Home: index.md
  - Overview: github_does_tools.md
  - Our Tools: our_tools.md
theme: readthedocs

plugins:
  - mkdocs-video

extra:
  homepage: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
